name: Build Windows EXE (PyInstaller)

on:
  workflow_dispatch:  # 수동 실행 버튼 활성화

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Python 설치
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow numpy tk

      # 4️⃣ EXE 빌드
      - name: Build EXE with PyInstaller
        shell: cmd
        run: |
          pyinstaller --noconfirm --clean --windowed --onefile ^
            --add-data "app;app" ^
            --name LongformBuilder ^
            app\longform_gui.py

      # 5️⃣ 결과물 업로드
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LongformBuilder-EXE
          path: dist/LongformBuilder.exe
